# Generated by Django 5.0.3 on 2024-03-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('Science', 'Science'), ('Sports', 'Sports'), ('History', 'History'), ('Pop', 'Pop'), ('Random', 'Random')], max_length=200, null=True, verbose_name='Topic'),
        ),
    ]
