# Generated by Django 5.0.3 on 2024-03-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_post_topic_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='thumbnails', verbose_name='Cover Image'),
        ),
    ]
