# Generated by Django 5.0.3 on 2024-04-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Caption'),
        ),
    ]
