# Generated by Django 5.0.3 on 2024-04-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_post_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Snippet'),
        ),
    ]
