# Generated by Django 5.0.3 on 2024-04-17 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_rename_tslug_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='head_image',
            new_name='head_imag',
        ),
    ]
