# Generated by Django 5.0.3 on 2024-04-17 02:03

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_rename_head_image_post_head_imag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='head_imag',
        ),
        migrations.AddField(
            model_name='post',
            name='head_image',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Cover Image'),
        ),
    ]
