# Generated by Django 5.0.3 on 2024-04-18 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_remove_post_head_imag_post_head_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='caption',
        ),
    ]
