# Generated by Django 5.0.3 on 2024-05-25 12:07

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_post_thumb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Cover Image'),
        ),
    ]
