# Generated by Django 5.0.3 on 2024-05-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_category_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='intro',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Snippet'),
        ),
    ]
