# Generated by Django 5.0.3 on 2024-05-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_category_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumb_image',
            new_name='thumbnail',
        ),
        migrations.AlterField(
            model_name='category',
            name='intro',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Intro'),
        ),
    ]
